/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.pilotD.cascadeeffects;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class FFProbabilityVisualPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final FFProbabilityWizardPanel model;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form FFProbabilityVisualPanel.
     *
     * @param  model  DOCUMENT ME!
     */
    public FFProbabilityVisualPanel(final FFProbabilityWizardPanel model) {
        this.model = model;

        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public FFProbabilityWizardPanel getModel() {
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING).addGap(0, 599, Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING).addGap(0, 450, Short.MAX_VALUE));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
