/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.pilotD.model;

import org.openide.util.NbBundle;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class ChooseEvacTimeVisualPanel_1 extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private final transient ChooseEvacTimeWizardPanel_1 model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cismap.commons.gui.MappingComponent mappingComponent1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ChooseEvacTimeVisualPanel.
     *
     * @param  model  DOCUMENT ME!
     */
    public ChooseEvacTimeVisualPanel_1(final ChooseEvacTimeWizardPanel_1 model) {
        this.model = model;

        initComponents();

        setName("Evacuation Model: Choose Evacuation Duration");
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public ChooseEvacTimeWizardPanel_1 getModel() {
        return model;
    }

    /**
     * DOCUMENT ME!
     */
    void init() {
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        mappingComponent1 = new de.cismet.cismap.commons.gui.MappingComponent();

        setBorder(javax.swing.BorderFactory.createTitledBorder(NbBundle.getMessage(ChooseEvacTimeVisualPanel_1.class, "ChooseEvacTimeVisualPanel_1.border.title"))); // NOI18N
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(mappingComponent1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
}
