/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.pilotD.model;

import org.openide.util.NbBundle;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class ChooseEQDateVisualPanel extends javax.swing.JPanel {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient Logger LOG = LoggerFactory.getLogger(ChooseEQDateVisualPanel.class);

    //~ Instance fields --------------------------------------------------------

    private final transient ChooseEQDateWizardPanel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ChooseEQDateVisualPanel.
     *
     * @param  model  DOCUMENT ME!
     */
    public ChooseEQDateVisualPanel(final ChooseEQDateWizardPanel model) {
        this.model = model;

        initComponents();

        jXDatePicker1.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(final ActionEvent e) {
                    setDate();
                }
            });
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {

                @Override
                public void insertUpdate(final DocumentEvent e) {
                    changedUpdate(e);
                }

                @Override
                public void removeUpdate(final DocumentEvent e) {
                    changedUpdate(e);
                }

                @Override
                public void changedUpdate(final DocumentEvent e) {
                    setDate();
                }
            });

        setName("Population Impact Model: Choose EQ Date");
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     */
    private void setDate() {
        final Calendar c = GregorianCalendar.getInstance();
        c.setTime(jXDatePicker1.getDate());
        try {
            final String[] s = jTextField1.getText().trim().split(":");
            c.set(Calendar.HOUR_OF_DAY, Integer.parseInt(s[0]));
            c.set(Calendar.MINUTE, Integer.parseInt(s[1]));
            model.setDate(c.getTime());
        } catch (Exception e) {
            LOG.warn("cannot parse time", e);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public ChooseEQDateWizardPanel getModel() {
        return model;
    }

    /**
     * DOCUMENT ME!
     */
    void init() {
        final Date date = (model.getDate() == null) ? new Date() : model.getDate();
        jXDatePicker1.setDate(date);
        final Calendar c = GregorianCalendar.getInstance();
        c.setTime(date);
        jTextField1.setText(c.get(Calendar.HOUR_OF_DAY) + ":" + ((c.get(Calendar.MINUTE) < 10) ? "0" : "")
                    + c.get(Calendar.MINUTE));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 0));

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(NbBundle.getMessage(ChooseEQDateVisualPanel.class, "ChooseEQDateVisualPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jXDatePicker1, gridBagConstraints);

        jLabel2.setText(NbBundle.getMessage(ChooseEQDateVisualPanel.class, "ChooseEQDateVisualPanel.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText(NbBundle.getMessage(
                ChooseEQDateVisualPanel.class,
                "ChooseEQDateVisualPanel.jTextField1.text")); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(60, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTextField1, gridBagConstraints);

        jLabel3.setText(NbBundle.getMessage(ChooseEQDateVisualPanel.class, "ChooseEQDateVisualPanel.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(filler1, gridBagConstraints);
    }                                                                                                                // </editor-fold>//GEN-END:initComponents
}
