/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.crisma.pilotD.model;

import org.jdesktop.beansbinding.Converter;

import org.openide.util.NbBundle;

import java.util.HashMap;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;

import de.cismet.cids.custom.crisma.pilotD.model.AreaEditorVisualPanel.Conv;
import de.cismet.cids.custom.crisma.pilotD.model.AreaEditorWizardPanel.Area;
import de.cismet.cids.custom.crisma.pilotD.model.AreaEditorWizardPanel.AreaEditor;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class PeopleCongestionEditor extends AreaEditor {

    //~ Enums ------------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    public enum EvacMeans {

        //~ Enum constants -----------------------------------------------------

        CAR, BUS, TRAIN, HELICOPTER, PLANE, ON_FOOT, BICYCLE
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form PeopleCongestionEditor.
     */
    public PeopleCongestionEditor() {
        initComponents();

        jSpinner1.setEditor(new JSpinner.NumberEditor(jSpinner1, "+0'%';-0'%'"));

        final DefaultComboBoxModel model = new DefaultComboBoxModel(EvacMeans.values());
        jComboBox1.setModel(model);
        jComboBox1.setSelectedItem(EvacMeans.CAR);
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public Area getArea() {
        return super.getArea(); // To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setArea(final Area a) {
        super.setArea(a); // To change body of generated methods, choose Tools | Templates.

        bindingGroup.unbind();
        bindingGroup.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(NbBundle.getMessage(PeopleCongestionEditor.class, "PeopleCongestionEditor.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${area.name}"),
                jTextField1,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTextField1, gridBagConstraints);

        jLabel2.setText(NbBundle.getMessage(PeopleCongestionEditor.class, "PeopleCongestionEditor.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        jSpinner1.setPreferredSize(new java.awt.Dimension(68, 28));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${area.value}"),
                jSpinner1,
                org.jdesktop.beansbinding.BeanProperty.create("value"),
                "val");
        binding.setSourceNullValue(0);
        binding.setConverter(new PConv());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSpinner1, gridBagConstraints);

        jSlider1.setMaximum(200);
        jSlider1.setValue(100);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                jSpinner1,
                org.jdesktop.beansbinding.ELProperty.create("${value}"),
                jSlider1,
                org.jdesktop.beansbinding.BeanProperty.create("value"),
                "a");
        binding.setConverter(new Conv());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSlider1, gridBagConstraints);

        jLabel3.setText(NbBundle.getMessage(PeopleCongestionEditor.class, "PeopleCongestionEditor.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${area.value}"),
                jComboBox1,
                org.jdesktop.beansbinding.BeanProperty.create("selectedItem"),
                "m");
        binding.setConverter(new MConv());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jComboBox1, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    //~ Inner Classes ----------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class PConv extends Converter<Object, Object> {

        //~ Methods ------------------------------------------------------------

        @Override
        public Object convertForward(final Object value) {
            return ((Map)value).get("perc");
        }

        @Override
        public Object convertReverse(final Object value) {
            if (getArea().value == null) {
                getArea().value = new HashMap();
            }

            ((Map)getArea().value).put("perc", value);

            return getArea().value;
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private final class MConv extends Converter<Object, Object> {

        //~ Methods ------------------------------------------------------------

        @Override
        public Object convertForward(final Object value) {
            return ((Map)value).get("means");
        }

        @Override
        public Object convertReverse(final Object value) {
            if (getArea().value == null) {
                getArea().value = new HashMap();
            }

            ((Map)getArea().value).put("means", value);

            return getArea().value;
        }
    }
}
